# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/rpc"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pborman/uuid"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.10"

[[constraint]]
  name = "github.com/keybase/go-codec"
  branch = "master"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  branch = "master"

[[constraint]]
  name = "github.com/syndtr/goleveldb"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  
[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"


[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"
