// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// ExitDao is an autogenerated mock type for the ExitDao type
type ExitDao struct {
	mock.Mock
}

// LastExitEventIdx provides a mock function with given fields:
func (_m *ExitDao) LastExitEventIdx() (uint64, error) {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveExitEventIdx provides a mock function with given fields: idx
func (_m *ExitDao) SaveExitEventIdx(idx uint64) error {
	ret := _m.Called(idx)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(idx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
