// Code generated by protoc-gen-go. DO NOT EDIT.
// source: root.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{0}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type BigInt struct {
	Hex                  string   `protobuf:"bytes,1,opt,name=hex,proto3" json:"hex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{1}
}
func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (dst *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(dst, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetHex() string {
	if m != nil {
		return m.Hex
	}
	return ""
}

type Input struct {
	DepositNonce         *BigInt  `protobuf:"bytes,2,opt,name=depositNonce,proto3" json:"depositNonce,omitempty"`
	BlockNum             uint64   `protobuf:"varint,3,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	TxIdx                uint32   `protobuf:"varint,4,opt,name=txIdx,proto3" json:"txIdx,omitempty"`
	OutIdx               uint32   `protobuf:"varint,5,opt,name=outIdx,proto3" json:"outIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{2}
}
func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (dst *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(dst, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetDepositNonce() *BigInt {
	if m != nil {
		return m.DepositNonce
	}
	return nil
}

func (m *Input) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Input) GetTxIdx() uint32 {
	if m != nil {
		return m.TxIdx
	}
	return 0
}

func (m *Input) GetOutIdx() uint32 {
	if m != nil {
		return m.OutIdx
	}
	return 0
}

type Output struct {
	Owner                []byte   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Amount               *BigInt  `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{3}
}
func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (dst *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(dst, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Output) GetAmount() *BigInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type BlockHeader struct {
	MerkleRoot           []byte   `protobuf:"bytes,1,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	RlpMerkleRoot        []byte   `protobuf:"bytes,2,opt,name=rlpMerkleRoot,proto3" json:"rlpMerkleRoot,omitempty"`
	PrevHash             []byte   `protobuf:"bytes,3,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Number               uint64   `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{4}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *BlockHeader) GetRlpMerkleRoot() []byte {
	if m != nil {
		return m.RlpMerkleRoot
	}
	return nil
}

func (m *BlockHeader) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Hash                 []byte       `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{5}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type TransactionBody struct {
	Input0               *Input   `protobuf:"bytes,1,opt,name=input0,proto3" json:"input0,omitempty"`
	Input0ConfirmSig     []byte   `protobuf:"bytes,2,opt,name=input0ConfirmSig,proto3" json:"input0ConfirmSig,omitempty"`
	Input1               *Input   `protobuf:"bytes,3,opt,name=input1,proto3" json:"input1,omitempty"`
	Input1ConfirmSig     []byte   `protobuf:"bytes,4,opt,name=input1ConfirmSig,proto3" json:"input1ConfirmSig,omitempty"`
	Output0              *Output  `protobuf:"bytes,5,opt,name=output0,proto3" json:"output0,omitempty"`
	Output1              *Output  `protobuf:"bytes,6,opt,name=output1,proto3" json:"output1,omitempty"`
	Fee                  *BigInt  `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	BlockNum             uint64   `protobuf:"varint,8,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	TxIdx                uint32   `protobuf:"varint,9,opt,name=txIdx,proto3" json:"txIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionBody) Reset()         { *m = TransactionBody{} }
func (m *TransactionBody) String() string { return proto.CompactTextString(m) }
func (*TransactionBody) ProtoMessage()    {}
func (*TransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{6}
}
func (m *TransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionBody.Unmarshal(m, b)
}
func (m *TransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionBody.Marshal(b, m, deterministic)
}
func (dst *TransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionBody.Merge(dst, src)
}
func (m *TransactionBody) XXX_Size() int {
	return xxx_messageInfo_TransactionBody.Size(m)
}
func (m *TransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionBody proto.InternalMessageInfo

func (m *TransactionBody) GetInput0() *Input {
	if m != nil {
		return m.Input0
	}
	return nil
}

func (m *TransactionBody) GetInput0ConfirmSig() []byte {
	if m != nil {
		return m.Input0ConfirmSig
	}
	return nil
}

func (m *TransactionBody) GetInput1() *Input {
	if m != nil {
		return m.Input1
	}
	return nil
}

func (m *TransactionBody) GetInput1ConfirmSig() []byte {
	if m != nil {
		return m.Input1ConfirmSig
	}
	return nil
}

func (m *TransactionBody) GetOutput0() *Output {
	if m != nil {
		return m.Output0
	}
	return nil
}

func (m *TransactionBody) GetOutput1() *Output {
	if m != nil {
		return m.Output1
	}
	return nil
}

func (m *TransactionBody) GetFee() *BigInt {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *TransactionBody) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *TransactionBody) GetTxIdx() uint32 {
	if m != nil {
		return m.TxIdx
	}
	return 0
}

type Transaction struct {
	Body                 *TransactionBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Sig0                 []byte           `protobuf:"bytes,2,opt,name=sig0,proto3" json:"sig0,omitempty"`
	Sig1                 []byte           `protobuf:"bytes,3,opt,name=sig1,proto3" json:"sig1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{7}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetBody() *TransactionBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Transaction) GetSig0() []byte {
	if m != nil {
		return m.Sig0
	}
	return nil
}

func (m *Transaction) GetSig1() []byte {
	if m != nil {
		return m.Sig1
	}
	return nil
}

type ConfirmedTransaction struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ConfirmSig0          []byte       `protobuf:"bytes,2,opt,name=confirmSig0,proto3" json:"confirmSig0,omitempty"`
	ConfirmSig1          []byte       `protobuf:"bytes,3,opt,name=confirmSig1,proto3" json:"confirmSig1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfirmedTransaction) Reset()         { *m = ConfirmedTransaction{} }
func (m *ConfirmedTransaction) String() string { return proto.CompactTextString(m) }
func (*ConfirmedTransaction) ProtoMessage()    {}
func (*ConfirmedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{8}
}
func (m *ConfirmedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmedTransaction.Unmarshal(m, b)
}
func (m *ConfirmedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmedTransaction.Marshal(b, m, deterministic)
}
func (dst *ConfirmedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmedTransaction.Merge(dst, src)
}
func (m *ConfirmedTransaction) XXX_Size() int {
	return xxx_messageInfo_ConfirmedTransaction.Size(m)
}
func (m *ConfirmedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmedTransaction proto.InternalMessageInfo

func (m *ConfirmedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ConfirmedTransaction) GetConfirmSig0() []byte {
	if m != nil {
		return m.ConfirmSig0
	}
	return nil
}

func (m *ConfirmedTransaction) GetConfirmSig1() []byte {
	if m != nil {
		return m.ConfirmSig1
	}
	return nil
}

type GetBalanceRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{9}
}
func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(dst, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type GetBalanceResponse struct {
	Balance              *BigInt  `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{10}
}
func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (dst *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(dst, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetBalance() *BigInt {
	if m != nil {
		return m.Balance
	}
	return nil
}

type GetOutputsRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Spendable            bool     `protobuf:"varint,2,opt,name=spendable,proto3" json:"spendable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOutputsRequest) Reset()         { *m = GetOutputsRequest{} }
func (m *GetOutputsRequest) String() string { return proto.CompactTextString(m) }
func (*GetOutputsRequest) ProtoMessage()    {}
func (*GetOutputsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{11}
}
func (m *GetOutputsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOutputsRequest.Unmarshal(m, b)
}
func (m *GetOutputsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOutputsRequest.Marshal(b, m, deterministic)
}
func (dst *GetOutputsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOutputsRequest.Merge(dst, src)
}
func (m *GetOutputsRequest) XXX_Size() int {
	return xxx_messageInfo_GetOutputsRequest.Size(m)
}
func (m *GetOutputsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOutputsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOutputsRequest proto.InternalMessageInfo

func (m *GetOutputsRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetOutputsRequest) GetSpendable() bool {
	if m != nil {
		return m.Spendable
	}
	return false
}

type GetOutputsResponse struct {
	ConfirmedTransactions []*ConfirmedTransaction `protobuf:"bytes,1,rep,name=confirmedTransactions,proto3" json:"confirmedTransactions,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *GetOutputsResponse) Reset()         { *m = GetOutputsResponse{} }
func (m *GetOutputsResponse) String() string { return proto.CompactTextString(m) }
func (*GetOutputsResponse) ProtoMessage()    {}
func (*GetOutputsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{12}
}
func (m *GetOutputsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOutputsResponse.Unmarshal(m, b)
}
func (m *GetOutputsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOutputsResponse.Marshal(b, m, deterministic)
}
func (dst *GetOutputsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOutputsResponse.Merge(dst, src)
}
func (m *GetOutputsResponse) XXX_Size() int {
	return xxx_messageInfo_GetOutputsResponse.Size(m)
}
func (m *GetOutputsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOutputsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOutputsResponse proto.InternalMessageInfo

func (m *GetOutputsResponse) GetConfirmedTransactions() []*ConfirmedTransaction {
	if m != nil {
		return m.ConfirmedTransactions
	}
	return nil
}

type GetBlockRequest struct {
	Number               uint64   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{13}
}
func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(dst, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type BlockMeta struct {
	CreatedAt            uint64   `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	TransactionCount     uint32   `protobuf:"varint,2,opt,name=transactionCount,proto3" json:"transactionCount,omitempty"`
	Fees                 *BigInt  `protobuf:"bytes,3,opt,name=fees,proto3" json:"fees,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMeta) Reset()         { *m = BlockMeta{} }
func (m *BlockMeta) String() string { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()    {}
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{14}
}
func (m *BlockMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMeta.Unmarshal(m, b)
}
func (m *BlockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMeta.Marshal(b, m, deterministic)
}
func (dst *BlockMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMeta.Merge(dst, src)
}
func (m *BlockMeta) XXX_Size() int {
	return xxx_messageInfo_BlockMeta.Size(m)
}
func (m *BlockMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMeta proto.InternalMessageInfo

func (m *BlockMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *BlockMeta) GetTransactionCount() uint32 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *BlockMeta) GetFees() *BigInt {
	if m != nil {
		return m.Fees
	}
	return nil
}

type GetBlockResponse struct {
	Block                 *Block                  `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ConfirmedTransactions []*ConfirmedTransaction `protobuf:"bytes,2,rep,name=confirmedTransactions,proto3" json:"confirmedTransactions,omitempty"`
	Metadata              *BlockMeta              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *GetBlockResponse) Reset()         { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()    {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{15}
}
func (m *GetBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponse.Unmarshal(m, b)
}
func (m *GetBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponse.Merge(dst, src)
}
func (m *GetBlockResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponse.Size(m)
}
func (m *GetBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponse proto.InternalMessageInfo

func (m *GetBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *GetBlockResponse) GetConfirmedTransactions() []*ConfirmedTransaction {
	if m != nil {
		return m.ConfirmedTransactions
	}
	return nil
}

func (m *GetBlockResponse) GetMetadata() *BlockMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SendRequest struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{16}
}
func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (dst *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(dst, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type SendResponse struct {
	Transaction          *Transaction          `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Inclusion            *TransactionInclusion `protobuf:"bytes,2,opt,name=inclusion,proto3" json:"inclusion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{17}
}
func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (dst *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(dst, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *SendResponse) GetInclusion() *TransactionInclusion {
	if m != nil {
		return m.Inclusion
	}
	return nil
}

type TransactionInclusion struct {
	MerkleRoot           []byte   `protobuf:"bytes,1,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TransactionIndex     uint32   `protobuf:"varint,3,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionInclusion) Reset()         { *m = TransactionInclusion{} }
func (m *TransactionInclusion) String() string { return proto.CompactTextString(m) }
func (*TransactionInclusion) ProtoMessage()    {}
func (*TransactionInclusion) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{18}
}
func (m *TransactionInclusion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInclusion.Unmarshal(m, b)
}
func (m *TransactionInclusion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInclusion.Marshal(b, m, deterministic)
}
func (dst *TransactionInclusion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInclusion.Merge(dst, src)
}
func (m *TransactionInclusion) XXX_Size() int {
	return xxx_messageInfo_TransactionInclusion.Size(m)
}
func (m *TransactionInclusion) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInclusion.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInclusion proto.InternalMessageInfo

func (m *TransactionInclusion) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *TransactionInclusion) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TransactionInclusion) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

type ConfirmRequest struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TransactionIndex     uint32   `protobuf:"varint,2,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	ConfirmSig0          []byte   `protobuf:"bytes,3,opt,name=confirmSig0,proto3" json:"confirmSig0,omitempty"`
	ConfirmSig1          []byte   `protobuf:"bytes,4,opt,name=confirmSig1,proto3" json:"confirmSig1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRequest) Reset()         { *m = ConfirmRequest{} }
func (m *ConfirmRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmRequest) ProtoMessage()    {}
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{19}
}
func (m *ConfirmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRequest.Unmarshal(m, b)
}
func (m *ConfirmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRequest.Merge(dst, src)
}
func (m *ConfirmRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmRequest.Size(m)
}
func (m *ConfirmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRequest proto.InternalMessageInfo

func (m *ConfirmRequest) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ConfirmRequest) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *ConfirmRequest) GetConfirmSig0() []byte {
	if m != nil {
		return m.ConfirmSig0
	}
	return nil
}

func (m *ConfirmRequest) GetConfirmSig1() []byte {
	if m != nil {
		return m.ConfirmSig1
	}
	return nil
}

type BlockHeightResponse struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeightResponse) Reset()         { *m = BlockHeightResponse{} }
func (m *BlockHeightResponse) String() string { return proto.CompactTextString(m) }
func (*BlockHeightResponse) ProtoMessage()    {}
func (*BlockHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{20}
}
func (m *BlockHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeightResponse.Unmarshal(m, b)
}
func (m *BlockHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeightResponse.Marshal(b, m, deterministic)
}
func (dst *BlockHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeightResponse.Merge(dst, src)
}
func (m *BlockHeightResponse) XXX_Size() int {
	return xxx_messageInfo_BlockHeightResponse.Size(m)
}
func (m *BlockHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeightResponse proto.InternalMessageInfo

func (m *BlockHeightResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type SyncRequest struct {
	Start                uint64   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_5a561a5bf11e14ee, []int{21}
}
func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (dst *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(dst, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "pb.EmptyRequest")
	proto.RegisterType((*BigInt)(nil), "pb.BigInt")
	proto.RegisterType((*Input)(nil), "pb.Input")
	proto.RegisterType((*Output)(nil), "pb.Output")
	proto.RegisterType((*BlockHeader)(nil), "pb.BlockHeader")
	proto.RegisterType((*Block)(nil), "pb.Block")
	proto.RegisterType((*TransactionBody)(nil), "pb.TransactionBody")
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*ConfirmedTransaction)(nil), "pb.ConfirmedTransaction")
	proto.RegisterType((*GetBalanceRequest)(nil), "pb.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "pb.GetBalanceResponse")
	proto.RegisterType((*GetOutputsRequest)(nil), "pb.GetOutputsRequest")
	proto.RegisterType((*GetOutputsResponse)(nil), "pb.GetOutputsResponse")
	proto.RegisterType((*GetBlockRequest)(nil), "pb.GetBlockRequest")
	proto.RegisterType((*BlockMeta)(nil), "pb.BlockMeta")
	proto.RegisterType((*GetBlockResponse)(nil), "pb.GetBlockResponse")
	proto.RegisterType((*SendRequest)(nil), "pb.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "pb.SendResponse")
	proto.RegisterType((*TransactionInclusion)(nil), "pb.TransactionInclusion")
	proto.RegisterType((*ConfirmRequest)(nil), "pb.ConfirmRequest")
	proto.RegisterType((*BlockHeightResponse)(nil), "pb.BlockHeightResponse")
	proto.RegisterType((*SyncRequest)(nil), "pb.SyncRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RootClient is the client API for Root service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RootClient interface {
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	GetOutputs(ctx context.Context, in *GetOutputsRequest, opts ...grpc.CallOption) (*GetOutputsResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmedTransaction, error)
	BlockHeight(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*BlockHeightResponse, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (Root_SyncClient, error)
}

type rootClient struct {
	cc *grpc.ClientConn
}

func NewRootClient(cc *grpc.ClientConn) RootClient {
	return &rootClient{cc}
}

func (c *rootClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/pb.Root/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootClient) GetOutputs(ctx context.Context, in *GetOutputsRequest, opts ...grpc.CallOption) (*GetOutputsResponse, error) {
	out := new(GetOutputsResponse)
	err := c.cc.Invoke(ctx, "/pb.Root/GetOutputs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.Root/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/pb.Root/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootClient) Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmedTransaction, error) {
	out := new(ConfirmedTransaction)
	err := c.cc.Invoke(ctx, "/pb.Root/Confirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootClient) BlockHeight(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*BlockHeightResponse, error) {
	out := new(BlockHeightResponse)
	err := c.cc.Invoke(ctx, "/pb.Root/BlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (Root_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Root_serviceDesc.Streams[0], "/pb.Root/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &rootSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Root_SyncClient interface {
	Recv() (*GetBlockResponse, error)
	grpc.ClientStream
}

type rootSyncClient struct {
	grpc.ClientStream
}

func (x *rootSyncClient) Recv() (*GetBlockResponse, error) {
	m := new(GetBlockResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RootServer is the server API for Root service.
type RootServer interface {
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	GetOutputs(context.Context, *GetOutputsRequest) (*GetOutputsResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
	Confirm(context.Context, *ConfirmRequest) (*ConfirmedTransaction, error)
	BlockHeight(context.Context, *EmptyRequest) (*BlockHeightResponse, error)
	Sync(*SyncRequest, Root_SyncServer) error
}

func RegisterRootServer(s *grpc.Server, srv RootServer) {
	s.RegisterService(&_Root_serviceDesc, srv)
}

func _Root_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Root/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Root_GetOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).GetOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Root/GetOutputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).GetOutputs(ctx, req.(*GetOutputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Root_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Root/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Root_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Root/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Root_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Root/Confirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).Confirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Root_BlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).BlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Root/BlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).BlockHeight(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Root_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RootServer).Sync(m, &rootSyncServer{stream})
}

type Root_SyncServer interface {
	Send(*GetBlockResponse) error
	grpc.ServerStream
}

type rootSyncServer struct {
	grpc.ServerStream
}

func (x *rootSyncServer) Send(m *GetBlockResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Root_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Root",
	HandlerType: (*RootServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Root_GetBalance_Handler,
		},
		{
			MethodName: "GetOutputs",
			Handler:    _Root_GetOutputs_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _Root_GetBlock_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Root_Send_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _Root_Confirm_Handler,
		},
		{
			MethodName: "BlockHeight",
			Handler:    _Root_BlockHeight_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _Root_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "root.proto",
}

func init() { proto.RegisterFile("root.proto", fileDescriptor_root_5a561a5bf11e14ee) }

var fileDescriptor_root_5a561a5bf11e14ee = []byte{
	// 966 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xaf, 0x13, 0x27, 0x4d, 0xc6, 0xe9, 0xb5, 0x4c, 0x73, 0xc5, 0x8a, 0x4e, 0x47, 0x58, 0x4e,
	0xba, 0x1c, 0x88, 0xaa, 0x29, 0x12, 0x88, 0x93, 0x90, 0x20, 0x07, 0xe2, 0x22, 0x74, 0x45, 0xda,
	0xf2, 0x8c, 0xe4, 0xd8, 0xdb, 0xc6, 0xba, 0xc4, 0x6b, 0xec, 0x35, 0x34, 0x8f, 0x48, 0x48, 0x3c,
	0xf1, 0xc6, 0x27, 0xe0, 0x03, 0xf0, 0x45, 0xf8, 0x52, 0x68, 0xd7, 0xbb, 0xf6, 0xe6, 0x9f, 0x0a,
	0x7d, 0xdb, 0xfd, 0xed, 0xec, 0xcc, 0x6f, 0xe7, 0x37, 0x33, 0x36, 0x40, 0xc6, 0xb9, 0x38, 0x4f,
	0x33, 0x2e, 0x38, 0x36, 0xd2, 0x19, 0x79, 0x04, 0xbd, 0x6f, 0x96, 0xa9, 0x58, 0x51, 0xf6, 0x53,
	0xc1, 0x72, 0x41, 0x06, 0xd0, 0x9e, 0xc4, 0xb7, 0xd3, 0x44, 0xe0, 0x09, 0x34, 0xe7, 0xec, 0xce,
	0x77, 0x86, 0xce, 0xa8, 0x4b, 0xe5, 0x92, 0xfc, 0xea, 0x40, 0x6b, 0x9a, 0xa4, 0x85, 0xc0, 0x73,
	0xe8, 0x45, 0x2c, 0xe5, 0x79, 0x2c, 0xae, 0x78, 0x12, 0x32, 0xbf, 0x31, 0x74, 0x46, 0xde, 0x25,
	0x9c, 0xa7, 0xb3, 0xf3, 0xf2, 0x36, 0x5d, 0x3b, 0xc7, 0x01, 0x74, 0x66, 0x0b, 0x1e, 0xbe, 0xbd,
	0x2a, 0x96, 0x7e, 0x73, 0xe8, 0x8c, 0x5c, 0x5a, 0xed, 0xb1, 0x0f, 0x2d, 0x71, 0x37, 0x8d, 0xee,
	0x7c, 0x77, 0xe8, 0x8c, 0x8e, 0x68, 0xb9, 0xc1, 0x33, 0x68, 0xf3, 0x42, 0x48, 0xb8, 0xa5, 0x60,
	0xbd, 0x23, 0x13, 0x68, 0x7f, 0x5f, 0x08, 0xc9, 0xa1, 0x0f, 0x2d, 0xfe, 0x4b, 0xc2, 0x32, 0xc5,
	0xb0, 0x47, 0xcb, 0x0d, 0x12, 0x68, 0x07, 0x4b, 0x5e, 0x24, 0x62, 0x07, 0x27, 0x7d, 0x42, 0x7e,
	0x77, 0xc0, 0x9b, 0xc8, 0xf0, 0xaf, 0x59, 0x10, 0xb1, 0x0c, 0x9f, 0x02, 0x2c, 0x59, 0xf6, 0x76,
	0xc1, 0x28, 0xe7, 0x42, 0xbb, 0xb3, 0x10, 0x7c, 0x06, 0x47, 0xd9, 0x22, 0x7d, 0x53, 0x9b, 0x34,
	0x94, 0xc9, 0x3a, 0x28, 0xdf, 0x98, 0x66, 0xec, 0xe7, 0xd7, 0x41, 0x3e, 0x57, 0x6f, 0xec, 0xd1,
	0x6a, 0x2f, 0x5f, 0x93, 0x14, 0xcb, 0x19, 0xcb, 0xd4, 0x23, 0x5d, 0xaa, 0x77, 0xe4, 0x6b, 0x68,
	0x29, 0x22, 0xf8, 0x1c, 0xda, 0x73, 0x45, 0x46, 0x85, 0xf7, 0x2e, 0x8f, 0x15, 0xed, 0x9a, 0x23,
	0xd5, 0xc7, 0x88, 0xe0, 0xce, 0x65, 0x84, 0x92, 0x82, 0x5a, 0x93, 0x7f, 0x1a, 0x70, 0xfc, 0x43,
	0x16, 0x24, 0x79, 0x10, 0x8a, 0x98, 0x27, 0x13, 0x1e, 0xad, 0xf0, 0x7d, 0x68, 0xc7, 0x52, 0xaa,
	0x0b, 0xed, 0xb0, 0x2b, 0x1d, 0x2a, 0xf1, 0xa8, 0x3e, 0xc0, 0x0f, 0xe1, 0xa4, 0x5c, 0xbd, 0xe2,
	0xc9, 0x4d, 0x9c, 0x2d, 0xaf, 0xe3, 0x5b, 0xed, 0x76, 0x0b, 0xaf, 0xdc, 0x8d, 0xd5, 0xd3, 0x76,
	0xb8, 0x1b, 0x57, 0xee, 0xc6, 0x96, 0x3b, 0xd7, 0x72, 0x67, 0xe1, 0xf8, 0x0c, 0x0e, 0xb9, 0x52,
	0xf1, 0x42, 0xc9, 0xab, 0x65, 0x2a, 0x85, 0xa5, 0xe6, 0xa8, 0xb6, 0x1a, 0xfb, 0xed, 0x7d, 0x56,
	0x63, 0x7c, 0x02, 0xcd, 0x1b, 0xc6, 0xfc, 0xc3, 0x2d, 0xb9, 0x25, 0xbc, 0x56, 0x79, 0x9d, 0x7d,
	0x95, 0xd7, 0xb5, 0x2a, 0x8f, 0xfc, 0x08, 0x9e, 0x95, 0x4c, 0x7c, 0x0e, 0xee, 0x8c, 0x47, 0x2b,
	0x9d, 0xc6, 0x53, 0xe9, 0x7f, 0x23, 0xd7, 0x54, 0x19, 0x48, 0x65, 0xf2, 0xf8, 0xf6, 0xc2, 0x28,
	0x23, 0xd7, 0x1a, 0x1b, 0xeb, 0x7a, 0x50, 0x6b, 0xf2, 0x87, 0x03, 0x7d, 0x9d, 0x0a, 0x16, 0xd9,
	0x91, 0xc6, 0xe0, 0x89, 0x7a, 0x6b, 0x17, 0x82, 0x65, 0x45, 0x6d, 0x1b, 0x1c, 0x82, 0x17, 0x56,
	0x59, 0x35, 0xa1, 0x6d, 0x68, 0xdd, 0xc2, 0x10, 0xb1, 0x21, 0xf2, 0x31, 0xbc, 0xf3, 0x2d, 0x13,
	0x93, 0x60, 0x11, 0x24, 0x21, 0xd3, 0x63, 0x00, 0x7d, 0x38, 0x0c, 0xa2, 0x28, 0x63, 0x79, 0xae,
	0xfb, 0xc1, 0x6c, 0xc9, 0x4b, 0x40, 0xdb, 0x3c, 0x4f, 0x79, 0x92, 0x33, 0x29, 0xd5, 0xac, 0x84,
	0x34, 0x6f, 0x5b, 0x08, 0x73, 0x44, 0xbe, 0x53, 0xa1, 0x4a, 0x01, 0xf3, 0x7b, 0x43, 0xe1, 0x13,
	0xe8, 0xe6, 0x29, 0x4b, 0xa2, 0x60, 0xb6, 0x28, 0x47, 0x4c, 0x87, 0xd6, 0x00, 0x89, 0x14, 0x91,
	0xca, 0x99, 0x26, 0x72, 0x05, 0x8f, 0xc3, 0x1d, 0xc9, 0x95, 0xbe, 0x9b, 0x23, 0xef, 0xd2, 0x97,
	0xb4, 0x76, 0x65, 0x9f, 0xee, 0xbe, 0x46, 0x5e, 0xc0, 0xb1, 0x7c, 0xae, 0x2c, 0x19, 0x43, 0xb8,
	0x6e, 0x66, 0x67, 0xad, 0x99, 0x0b, 0xe8, 0x2a, 0xbb, 0x37, 0x4c, 0x04, 0x92, 0x7b, 0x98, 0xb1,
	0x40, 0xb0, 0xe8, 0x2b, 0xa1, 0xed, 0x6a, 0x40, 0xf6, 0x8a, 0x25, 0xe3, 0xab, 0x6a, 0x5e, 0x1d,
	0xd1, 0x2d, 0x1c, 0x9f, 0x82, 0x7b, 0xc3, 0x58, 0xae, 0x1b, 0xcf, 0xce, 0xab, 0xc2, 0xc9, 0xdf,
	0x0e, 0x9c, 0xd4, 0x14, 0x75, 0x1a, 0xde, 0x83, 0x96, 0x2a, 0x73, 0xbb, 0xfb, 0x4b, 0x8b, 0x12,
	0xdf, 0x9f, 0xa7, 0xc6, 0x83, 0xf2, 0x84, 0x2f, 0xa0, 0xb3, 0x64, 0x22, 0x88, 0x02, 0x11, 0x68,
	0xa6, 0x47, 0x55, 0x4c, 0x99, 0x10, 0x5a, 0x1d, 0x93, 0x2f, 0xc1, 0xbb, 0x66, 0x49, 0x64, 0xd2,
	0xf9, 0xff, 0xcb, 0x9e, 0xac, 0xa0, 0x57, 0x7a, 0xd0, 0xaf, 0x7d, 0x40, 0xe7, 0x7c, 0x0a, 0xdd,
	0x38, 0x09, 0x17, 0x45, 0x2e, 0x2f, 0x94, 0x9f, 0x0a, 0x7f, 0xe3, 0xc2, 0xd4, 0x9c, 0xd3, 0xda,
	0x94, 0xfc, 0xe6, 0x40, 0x7f, 0x97, 0xcd, 0xbd, 0x1f, 0x91, 0x21, 0x78, 0x66, 0xf0, 0xc8, 0xd2,
	0x69, 0xa8, 0x92, 0xb0, 0xa1, 0x8d, 0xa2, 0x98, 0x26, 0x11, 0xbb, 0x53, 0xa9, 0x5c, 0x2f, 0x0a,
	0x85, 0x93, 0xbf, 0x1c, 0x78, 0xa4, 0xe5, 0x31, 0x79, 0xdc, 0x08, 0xe0, 0xfc, 0xb7, 0x00, 0x8d,
	0xdd, 0x01, 0x36, 0x27, 0x4b, 0xf3, 0xde, 0xc9, 0xe2, 0xee, 0x9a, 0x2c, 0xa7, 0xfa, 0x13, 0x16,
	0xdf, 0xce, 0x45, 0xa5, 0xd6, 0x99, 0xfc, 0xd6, 0x49, 0xc4, 0xf4, 0x4f, 0xb9, 0x23, 0x1f, 0x80,
	0x77, 0xbd, 0x4a, 0x42, 0xf3, 0x9e, 0x3e, 0xb4, 0x72, 0x11, 0x64, 0xc6, 0xaa, 0xdc, 0x5c, 0xfe,
	0xd9, 0x04, 0x57, 0xe5, 0xf3, 0x0b, 0x80, 0x7a, 0x0e, 0xe1, 0x63, 0xa9, 0xdd, 0xd6, 0x18, 0x1b,
	0x9c, 0x6d, 0xc2, 0x25, 0x05, 0x72, 0xa0, 0xaf, 0xeb, 0xe9, 0x51, 0x5d, 0x5f, 0x1f, 0x4d, 0xd5,
	0xf5, 0x8d, 0x21, 0x43, 0x0e, 0xf0, 0x33, 0xe8, 0x98, 0x9e, 0xc3, 0x53, 0x13, 0xc4, 0x1a, 0x12,
	0x83, 0xfe, 0x3a, 0x58, 0x5d, 0xfc, 0x08, 0x5c, 0x59, 0xba, 0xa8, 0xaa, 0xd3, 0x6a, 0x83, 0xc1,
	0x49, 0x0d, 0x54, 0xc6, 0x9f, 0xc3, 0xa1, 0x16, 0x19, 0xd1, 0x6a, 0x48, 0x73, 0x65, 0x6f, 0x93,
	0x92, 0x03, 0x7c, 0x59, 0xfd, 0xe2, 0xc8, 0xdc, 0xa2, 0xf2, 0x6e, 0xff, 0xe8, 0x0d, 0xde, 0xb5,
	0xfe, 0x30, 0x6c, 0x79, 0xc8, 0x01, 0x8e, 0xc1, 0x95, 0x42, 0x68, 0x8e, 0xb5, 0x24, 0xfb, 0x1e,
	0x75, 0xe1, 0xcc, 0xda, 0xea, 0x8f, 0xf2, 0x93, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x89, 0x22,
	0x20, 0x17, 0x5f, 0x0a, 0x00, 0x00,
}
