// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/kyokan/plasma/rpc"

// RootClient is an autogenerated mock type for the RootClient type
type RootClient struct {
	mock.Mock
}

// GetBlock provides a mock function with given fields: height
func (_m *RootClient) GetBlock(height uint64) *rpc.GetBlocksResponse {
	ret := _m.Called(height)

	var r0 *rpc.GetBlocksResponse
	if rf, ok := ret.Get(0).(func(uint64) *rpc.GetBlocksResponse); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetBlocksResponse)
		}
	}

	return r0
}

// GetUTXOs provides a mock function with given fields: userAddress
func (_m *RootClient) GetUTXOs(userAddress string) *rpc.GetUTXOsResponse {
	ret := _m.Called(userAddress)

	var r0 *rpc.GetUTXOsResponse
	if rf, ok := ret.Get(0).(func(string) *rpc.GetUTXOsResponse); ok {
		r0 = rf(userAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.GetUTXOsResponse)
		}
	}

	return r0
}
